version: "2.1"
services:
  trup:
    image: trup
    build: ./
    container_name: trup
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://trup_postgres/trup"
    depends_on:
      trup_postgres:
        condition: service_healthy

  trup_postgres:
    build: ./db
    container_name: trup_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD:
      POSTGRES_DB: trup
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=root --dbname=trup"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./db/structure.sql:/docker-entrypoint-initdb.d/structure.sql
      #- ./postgres_data:/var/lib/postgresql/data/
