apiVersion: ENC[AES256_GCM,data:Neo=,iv:9YhMfRCcJ0F7EYTcq9SYmtTi4Mt/j37Bvtis5/3Obg8=,tag:zMrcVr6o00kQB10inOxJow==,type:str]
kind: ENC[AES256_GCM,data:gjWTBoFM,iv:A+FSE0Fq4milZsFLk8GsNXh5swi9985Und/dmoJJtYs=,tag:/0G5qI9P/ui3T14lUBy58A==,type:str]
type: ENC[AES256_GCM,data:qySrtnNg,iv:8pAJBL+yufOy5tDZy1z16FM6VoNRHKNueNbfOKXT/Bk=,tag:tfk3Ryl5aAGxSRrx6x3jug==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Pxo/JPt8XmT2TM9QVA==,iv:6yc4/HZ1qO7jC3dVhhJKTl/oMjOCaVp+A8vQhi4podk=,tag:HNgim16JSovr7itdgTwqKQ==,type:str]
    namespace: ENC[AES256_GCM,data:XJdvGg==,iv:+bbO+/C/gOGLB4NSgZzWSKSQlUvW6IC68pwFZvPyNSM=,tag:5iTuxlYQl+QhSyG82d8BoA==,type:str]
stringData:
    TOKEN: ENC[AES256_GCM,data:I8HYmjXLtmcRdshgo4trg5vuJHnH/QhSY3sRf7VmQ9GpSQpJzefNiU8VrkaiM1Wvrcqiu/0nNcRVN1I=,iv:/VM2Y2LYiu7OdUYHh9u2opLNHZnh/ehprJ5fEjhypvU=,tag:aUbv0V8Q9e/W6WVsVMJndw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2021-02-02T14:42:08Z'
    mac: ENC[AES256_GCM,data:yzZX2AOasgjTFXuUgTPZ+EqLxoAmlUhegg8NuIpuSY8mVCJrQZ5NiLPVAI8vzgtaXkLbbhspQN2n0PaT/8KfSuYnpKkdH5YdRzhuT0kBHLBWuYV8vVt8KfOnQVQm1ZtaWkFGpllf6sMfAPx/ocB+OCGCfgdlwMH2hIrHIT9U9So=,iv:k9vgC5ZgSzADqbNMMcuUSxHJIrCL2bqS6mZuNa3mdiY=,tag:Uj53vl6w1Fjtfd3tzHchzQ==,type:str]
    pgp:
    -   created_at: '2021-02-02T14:36:03Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxWJ1LW99RiaARAAhAnRQejTH7De4bgnttExu6XysxuPZEovDvWDM/R1PfZI
            WFwx+09sQsGA3BZiWcjGiLAhdYXTVtgoXMeoD0YRZgWE1lt1lToIJg189bu86Hua
            hGrvbPSfa4HyO2redfAaeBYFXMULWb0Dh0LzV27L+5jctK4tyDAUkjvF0ZzsBGi+
            huHYc9mHMArim0uzGgkzN0i7Vfnboc/xasEh1JvdhUo1zmdg/F2ud3Qf6HNwbX+K
            RmsZSvgFe+bE8DEbCQDc5EBNMdXm2hUpxzkOaSKWy1IJbhB3tGcOjPkS1vJQ/cBS
            nXrvaI762adC8nqrhEkwPv/VdwlPDPDdh6vafOKOO8231cirW9OMOQHpkxm7AnhD
            ZfyOhn56DjsCHDoBhcifWwYlCP0gXOHZ1fCAGVLMaa0O+d9ZHs87QE9dKA8h5h8X
            OaolFPxyNB3s1MJqC8zlvcM0JX2WUNQY7+zRSPDvwyMUmTUN0u5oUVK57is7kpO7
            SErwuSHZWjVBCqvj+bGxc+Qm0lk1spQqyOKuIIZs+cLwTE2LFpegnzeDM6BtV26g
            lv98ShQa2iQcQAvzpl1hLxnrjtRzaCc9QB/OKWd6KChRUdNNh95C1ZIk+nIQI62Q
            WmXRw8JTU/PzwGqsgcaMkBJgJBCn7JS9hrDIC1MW4S7ye7KpKh9BaTdx2n914q3S
            XAEvI1KWDpO4C3sU8seuv5uofVm6vTqPDu9KFlBMDscLJtezK4u8U1XwS7kEIotJ
            FsQ5HOeTWeEGlJXF3jhmI5WZ/LB1zVE8BXe+8jvyeQDgGd+9OCof9ug/YsGZ
            =rBbG
            -----END PGP MESSAGE-----
        fp: A23DAC7B327ABD4886AADDAED9FE322E367F575D
    unencrypted_suffix: _unencrypted
    version: 3.5.0
